In [1]:
import numpy as np

In [2]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

# 1. An array object of arbitrary homogeneous items

## 1.1. La nivel de tipuri de date

In [5]:
arr = np.array([1, 2, 3, 4])
arr, type(arr)

(array([1, 2, 3, 4]), numpy.ndarray)

In [6]:
arr = np.array([1, 2, 3, 4, True])
arr, type(arr)

(array([1, 2, 3, 4, 1]), numpy.ndarray)

In [7]:
arr = np.array([1, 2, 3, 4, True, "salutare"])
arr, type(arr)

(array(['1', '2', '3', '4', 'True', 'salutare'], dtype='<U21'), numpy.ndarray)

In [8]:
arr = np.array([1, 2, 3, 4, True, 56.312])
arr, type(arr)

(array([ 1.   ,  2.   ,  3.   ,  4.   ,  1.   , 56.312]), numpy.ndarray)

In [10]:
type(arr), arr.dtype

(numpy.ndarray, dtype('float64'))

In [11]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [12]:
arr = np.array([1, 2, 3, 4], dtype=np.int8)
arr.dtype

dtype('int8')

In [13]:
2 ** 8

256

In [14]:
#0..255

In [15]:
arr = np.array([1, 2, 3, 0, 255], dtype=np.int8)
arr.dtype

OverflowError: Python integer 255 out of bounds for int8

In [17]:
arr = np.array([1, 2, 3, 0, 255], dtype=np.uint8)
arr

array([  1,   2,   3,   0, 255], dtype=uint8)

In [18]:
arr = np.array([1, 2, 3, 0, 255, 256], dtype=np.uint8)
arr

OverflowError: Python integer 256 out of bounds for uint8

In [19]:
arr = np.array([1, 2, 3, 0, -128, 127], dtype=np.int8)
arr

array([   1,    2,    3,    0, -128,  127], dtype=int8)

In [20]:
arr = np.array([1, 2, 3, 0, -128, 128], dtype=np.int8)
arr

OverflowError: Python integer 128 out of bounds for int8

In [21]:
arr = np.array([1, 2, 3, 0, -129, 127], dtype=np.int8)
arr

OverflowError: Python integer -129 out of bounds for int8

## 1.2. La nivel de forma

In [22]:
lista = [1, 2, 3, [50, 60]]
lista

[1, 2, 3, [50, 60]]

In [28]:
arr = np.array([[1, 2, 3], [50, 60, 70]])
arr

array([[ 1,  2,  3],
       [50, 60, 70]])

In [29]:
arr = np.array([[1, 2, 3, None], [50, 60, 70, 80]])
arr

array([[1, 2, 3, None],
       [50, 60, 70, 80]], dtype=object)

In [30]:
arr = np.array([[1, 2, 3, np.nan], [50, 60, 70, 80]])
arr

array([[ 1.,  2.,  3., nan],
       [50., 60., 70., 80.]])

In [31]:
arr = np.array([[1, 2, 3], [50, 60, 70, 80]])
arr

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [32]:
arr = np.array([[1, 2, 3, np.nan], [50, 60, 70, 80]])
arr

array([[ 1.,  2.,  3., nan],
       [50., 60., 70., 80.]])

In [33]:
len(arr)

2

In [34]:
arr.size

8

In [35]:
arr.shape

(2, 4)

#  2. Fast mathematical operations over arrays

In [37]:
range(10)

range(0, 10)

In [38]:
arr = np.array(range(2, 8))
arr

array([2, 3, 4, 5, 6, 7])

In [39]:
arr = np.arange(2, 8)
arr

array([2, 3, 4, 5, 6, 7])

In [40]:
arr = np.arange(2, 8, dtype=np.int8)
arr

array([2, 3, 4, 5, 6, 7], dtype=int8)

In [41]:
arr - 1

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [42]:
arr ** 2

array([ 4,  9, 16, 25, 36, 49], dtype=int8)

In [43]:
arr1 = np.arange(102, 108)
arr2 = np.arange(2, 8)
print("arr1=", arr1)
print("arr2=", arr2)

arr1= [102 103 104 105 106 107]
arr2= [2 3 4 5 6 7]


In [44]:
arr1 - arr2

array([100, 100, 100, 100, 100, 100])

In [45]:
arr1 = np.arange(102, 110)
arr2 = np.arange(2, 8)

arr1 - arr2

ValueError: operands could not be broadcast together with shapes (8,) (6,) 