In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

# Operatii numpy - matematice

In [3]:
arr = np.array([10, 15, 17, 18, 20, 23, 25])
arr

array([10, 15, 17, 18, 20, 23, 25])

In [4]:
arr ** 2

array([100, 225, 289, 324, 400, 529, 625])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0])

# Operatii numpy - logice

In [6]:
arr 

array([10, 15, 17, 18, 20, 23, 25])

In [7]:
arr_rezultat = arr > 20
arr_rezultat

array([False, False, False, False, False,  True,  True])

In [8]:
type(arr_rezultat)

numpy.ndarray

In [9]:
arr

array([10, 15, 17, 18, 20, 23, 25])

In [10]:
arr[arr_rezultat]

array([23, 25])

In [11]:
arr

array([10, 15, 17, 18, 20, 23, 25])

In [12]:
arr[ arr > 20 ]

array([23, 25])

In [13]:
arr 

array([10, 15, 17, 18, 20, 23, 25])

In [14]:
arr [ arr >= 17 and arr <= 18 ]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
arr [ (arr >= 17) and (arr <= 18) ]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
arr [ (arr >= 17) & (arr <= 18) ]

array([17, 18])

In [ ]:
lista = [10, 15, 17, 18, 20, 23, 25]

In [ ]:

list(filter(lambda x: x>17, arr))

[np.int64(18), np.int64(20), np.int64(23), np.int64(25)]

In [ ]:
list(filter(lambda x: x>17 and x<=18, arr))

[np.int64(18)]

In [ ]:
list(filter(lambda x: x>=17 and x<=18, arr))

[np.int64(17), np.int64(18)]

In [ ]:
def fitrarea_custom(x):
    return x>=17 and x<=18
list(filter(fitrarea_custom, arr))

[np.int64(17), np.int64(18)]

In [ ]:
arr = np.array([10, 15, 17, 18, 20, 23, 25])
arr

array([10, 15, 17, 18, 20, 23, 25])

In [ ]:
arr[ (arr < 16) | (arr > 22) ]

array([10, 15, 23, 25])

In [ ]:
arr[ arr < 16 | arr > 22 ] # nu sunt paranteze

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
conditie1 = arr < 16
conditie2 =  arr > 22
arr[ conditie1 | conditie2 ]

array([17, 18, 20, 23, 25])

# Indexi

In [ ]:
#        0. 1  2. 3  4. 5
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista[0:5]

[1, 2, 3, 4, 5]

In [ ]:
lista[:5]

[1, 2, 3, 4, 5]

In [ ]:
lista[-5:]

[6, 7, 8, 9, 10]

In [ ]:
lista[-1]

10

In [ ]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
lista[3] = 0
lista

[1, 2, 3, 0, 5, 6, 7, 8, 9, 10]

In [ ]:
lista[3:6] = 0

TypeError: must assign iterable to extended slice

In [ ]:
lista[3:6] = [0, 0, 0]

In [ ]:
lista


[1, 2, 3, 0, 0, 0, 7, 8, 9, 10]

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[3:6] = 0
arr

array([ 1,  2,  3,  0,  0,  0,  7,  8,  9, 10])

# Reshaping

In [16]:
arr.shape

(10,)

In [17]:
arr.size

10

In [18]:
arr.reshape((2, 5))

array([[ 1,  2,  3,  0,  0],
       [ 0,  7,  8,  9, 10]])

In [19]:
arr.reshape((5, 2))

array([[ 1,  2],
       [ 3,  0],
       [ 0,  0],
       [ 7,  8],
       [ 9, 10]])

In [20]:
arr.reshape((2, 6))

ValueError: cannot reshape array of size 10 into shape (2,6)

In [21]:
arr.reshape((2, 5, 1))

array([[[ 1],
        [ 2],
        [ 3],
        [ 0],
        [ 0]],

       [[ 0],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [22]:
arr

array([ 1,  2,  3,  0,  0,  0,  7,  8,  9, 10])

In [23]:
arr.reshape((1, -1))

array([[ 1,  2,  3,  0,  0,  0,  7,  8,  9, 10]])

In [24]:
arr.reshape((-1, 1))

array([[ 1],
       [ 2],
       [ 3],
       [ 0],
       [ 0],
       [ 0],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [25]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
arr = arr.reshape((5, 20))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [28]:
arr[2][1]

np.int64(41)

In [31]:
arr[2, 1]

np.int64(41)

In [32]:
arr[ : , 1]

array([ 1, 21, 41, 61, 81])

In [33]:
arr[: , 0]

array([ 0, 20, 40, 60, 80])

In [34]:
arr[0, :]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
lista = [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]]

lista[2][1]

41