In [12]:
import numpy as np

# pip install Pillow

In [13]:
from PIL import Image

In [14]:
imagine_citita =  Image.open("imagine.png")
imagine_citita

In [15]:
type(imagine_citita)

PIL.PngImagePlugin.PngImageFile

In [16]:
np_image = np.array(imagine_citita)
np_image

array([[[205, 176, 153, 255],
        [112, 208, 113, 255],
        [ 93, 220, 110, 255],
        [233, 219, 222, 255],
        [151,  45, 190, 255],
        [178, 113, 224, 255],
        [225, 196, 241, 255],
        [194,  66, 150, 255],
        [225, 199, 243, 255],
        [251, 237, 242, 255]],

       [[249, 224, 224, 255],
        [252, 238, 238, 255],
        [251, 233, 233, 255],
        [227, 125, 125, 255],
        [245, 208, 208, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [245, 208, 221, 255],
        [255, 255, 255, 255],
        [232, 145, 174, 255]],

       [[149, 149, 149, 255],
        [160, 160, 160, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [253, 244, 247, 255],
        [225, 114, 152, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [102, 102, 102, 255],
    

In [17]:
np_image.shape

(10, 10, 4)

# Matplotlib

In [18]:
np_image[0]

array([[205, 176, 153, 255],
       [112, 208, 113, 255],
       [ 93, 220, 110, 255],
       [233, 219, 222, 255],
       [151,  45, 190, 255],
       [178, 113, 224, 255],
       [225, 196, 241, 255],
       [194,  66, 150, 255],
       [225, 199, 243, 255],
       [251, 237, 242, 255]], dtype=uint8)

In [19]:
np_image[0] = [0, 255, 0, 255]
np_image

array([[[  0, 255,   0, 255],
        [  0, 255,   0, 255],
        [  0, 255,   0, 255],
        [  0, 255,   0, 255],
        [  0, 255,   0, 255],
        [  0, 255,   0, 255],
        [  0, 255,   0, 255],
        [  0, 255,   0, 255],
        [  0, 255,   0, 255],
        [  0, 255,   0, 255]],

       [[249, 224, 224, 255],
        [252, 238, 238, 255],
        [251, 233, 233, 255],
        [227, 125, 125, 255],
        [245, 208, 208, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [245, 208, 221, 255],
        [255, 255, 255, 255],
        [232, 145, 174, 255]],

       [[149, 149, 149, 255],
        [160, 160, 160, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [253, 244, 247, 255],
        [225, 114, 152, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [102, 102, 102, 255],
    

In [21]:
new_image = Image.fromarray(np_image)
new_image.save("verde_sus.png")

Red_Green_Blue = [0, 255, 0, 255]