In [1]:
import numpy as np
from PIL import Image

In [7]:
SCALE = 10
WIDTH = 3 * SCALE
HEIGHT = 2 * SCALE

In [3]:
np_array = np.ones((2, 3))
np_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np_array = np.zeros((2, 3))
np_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np_array = np.ones((2, 3)) * 100
np_array

array([[100., 100., 100.],
       [100., 100., 100.]])

In [24]:
np_array = np.ones((HEIGHT, WIDTH), dtype=np.uint8) * 255


In [23]:
new_image = Image.fromarray(np_array)
new_image.save("steag_alb.png")

In [25]:
np_array = np.ones((HEIGHT, WIDTH, 3), dtype=np.uint8) * 255

In [30]:
RED = 	[0,43,127]
YELLOW = [252,209,22]	
BLUE = [206,17, 38]

In [27]:
np_array.shape

(20, 30, 3)

In [28]:
np_array

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [31]:
np_array[ : , 0 : WIDTH // 3, : ] = BLUE
np_array[ : , WIDTH // 3 : 2 * (WIDTH // 3), : ] = YELLOW
np_array[ : ,  2 * (WIDTH // 3) : , : ] = RED

In [32]:
new_image = Image.fromarray(np_array)
new_image.save("steag_romania.png")