In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
def relu_activare(z):
    return max(0, z)

def tanh_activare(z):
    return np.tanh(z)

def relu_derivata(a):
    # a = relu(z); derivata e 1 acolo unde a>0, 0 in rest
    return (a > 0).astype(float)

In [16]:
np.random.random()

0.07025036964244602

In [6]:
rng = np.random.RandomState(42)
rng.randn(1, 10)

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004]])

In [7]:
w1 = rng.randn(1, 4)
w1

array([[-0.46341769, -0.46572975,  0.24196227, -1.91328024]])

In [9]:
b1 = np.zeros((1,4 ))
b1 

array([[0., 0., 0., 0.]])

In [1]:
## Vreau sa creez o functie cu
#   -  x, y
#.  - nr de straturi
#   - functie de activare
#   - learning rate(alpha) -> folosit pentru ajustarea ponderilor greutatilor
#   - nr de epoci


def antreneaza_retea(x, y, nr_strat, func_activare, derivata_activare, alpha, epoci, random_state = 42):
    rng = np.random.RandomState(random_state) # 42 - un numar random, care este reproductibil
    w1 = rng.randn(1, nr_strat) 
    b1 = np.zeros((1,nr_strat ))

    w2 = rng.randn(1, nr_strat) 
    b2 = np.zeros((1,nr_strat ))

    istoric_pierderi = []

    n = len(x)

    for i in range(epoci):
        # forward
        y1 = x @ w1 + b1
        a1 = func_activare(y1)

        y2 = a1 @ w2 + b2 # y_pred
        y_pred = y2

        loss = np.mean((y_pred - y) ** 2)
        istoric_pierderi.append(loss)

        ## backwards
        grad_y2 = (2 / n) * (y_pred - y)
        grad_w2 = a1.T @ grad_y2
        errori0 = y_pred - y
        grad_w2 = (2 / n) * (a1.T @ errori0)
        grad_b2 = np.sum(grad_w2, axis=0, keepdims=True)

        grad_a1 = grad_y2 @ w2.T
        grad_w1 = x.T @ derivata_activare(a1)
        grad_b1 = np.sum(grad_w1, axis=0, keepdims=True)

        w2 = w2 - alpha * grad_w2
        b2 = b2 - alpha * grad_b2


        w1 = w1 - alpha * grad_w1
        b1 = b1 - alpha * grad_b1

        









In [ ]:
# antreneaza_retea(x=suprafete, y=preturi, nr_strat=4, func_activare=relu_activare, alpha=0.1, epoci=100, random_state = 42)